# Generated by Django 4.1.7 on 2023-03-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=40)),
                ('source', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=40)),
                ('text', models.TextField()),
            ],
        ),
    ]
