# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=40)),
                ('source', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=40)),
                ('text', models.TextField()),
            ],
        ),
    ]
